spring:
  application:
    name: eureka-server
server:
  port: ${zss.eureka1.port}
eureka:
  instance:
    hostname: ${zss.eureka1.host}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  server: 
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ipAddress}:${server.port}/eureka/

logging:
  config: ${log.path}/logback.xml

zss:
  eureka1:
    host: peer1
    port: 8761
  eureka2:
    host: peer2
    port: 8762
  eureka3:
    host: peer3
    port: 8763